site_name: Daniel Kelshaw
site_url: https://danielkelshaw.com

theme:

  name: material
  language: en

  palette:

    # palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  features:
    - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - content.code.copy
    - content.code.annotate
    - content.tabs.link

  icon:
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle

extra:

  social:

    - icon: fontawesome/brands/twitter
      link: https://twitter.com/danielkelshaw

    - icon: fontawesome/brands/github
      link: https://github.com/danielkelshaw

    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/danielkelshaw

  generator: false

plugins: []

markdown_extensions:

  # tooltips
  - abbr
  - attr_list
  - pymdownx.snippets

  # annotations (w/ attr_list)
  - md_in_html
  - pymdownx.superfences

  # admonitions (w/ pymdownx.superfences)
  - admonition
  - pymdownx.details

  # custom lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  # code blocks (w/ pydownx.snippets, pydownx.superfences)
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite

  # tabs (w/ pymdownx.superfences)
  - pymdownx.tabbed:
      alternate_style: true

  # footnotes
  - footnotes

  # formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # smart symbols
  - pymdownx.smartsymbols

  # maths
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


repo_url: https://github.com/danielkelshaw
repo_name: danielkelshaw

copyright: Copyright &copy; 2023 Daniel Kelshaw

extra_css:
  - stylesheets/extra.css

nav:

  - Home: index.md
  - Publications: publications.md
  - Software: software.md
  - Contact: contact.md
